<?php
/**
 * GoogleSearchConsoleApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Manager
 *
 * Subscription management and related services.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@wordlift.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * GoogleSearchConsoleApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GoogleSearchConsoleApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'listWebsiteSearch' => [
            'application/json',
        ],
        'listWebsites' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation listWebsiteSearch
     *
     * List Website Search data
     *
     * @param  string $website The website URL (required)
     * @param  string $since The start date, inclusive, in yyyy-MM-dd format. (required)
     * @param  string $until The end date, inclusive, in yyyy-MM-dd format. (required)
     * @param  string[] $dimensions The dimensions, e.g. &#x60;query&#x60;, &#x60;page&#x60;. Must repeat for each dimension. (required)
     * @param  string $google_access_token The Google access token, must have access to the Google Search Console scope (required)
     * @param  string $cursor The cursor (optional)
     * @param  int $limit The maximum number of results (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listWebsiteSearch'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\PageWebsiteSearch
     */
    public function listWebsiteSearch($website, $since, $until, $dimensions, $google_access_token, $cursor = null, $limit = 10, string $contentType = self::contentTypes['listWebsiteSearch'][0])
    {
        list($response) = $this->listWebsiteSearchWithHttpInfo($website, $since, $until, $dimensions, $google_access_token, $cursor, $limit, $contentType);
        return $response;
    }

    /**
     * Operation listWebsiteSearchWithHttpInfo
     *
     * List Website Search data
     *
     * @param  string $website The website URL (required)
     * @param  string $since The start date, inclusive, in yyyy-MM-dd format. (required)
     * @param  string $until The end date, inclusive, in yyyy-MM-dd format. (required)
     * @param  string[] $dimensions The dimensions, e.g. &#x60;query&#x60;, &#x60;page&#x60;. Must repeat for each dimension. (required)
     * @param  string $google_access_token The Google access token, must have access to the Google Search Console scope (required)
     * @param  string $cursor The cursor (optional)
     * @param  int $limit The maximum number of results (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listWebsiteSearch'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\PageWebsiteSearch, HTTP status code, HTTP response headers (array of strings)
     */
    public function listWebsiteSearchWithHttpInfo($website, $since, $until, $dimensions, $google_access_token, $cursor = null, $limit = 10, string $contentType = self::contentTypes['listWebsiteSearch'][0])
    {
        $request = $this->listWebsiteSearchRequest($website, $since, $until, $dimensions, $google_access_token, $cursor, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\PageWebsiteSearch' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\PageWebsiteSearch' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\PageWebsiteSearch', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\PageWebsiteSearch';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\PageWebsiteSearch',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listWebsiteSearchAsync
     *
     * List Website Search data
     *
     * @param  string $website The website URL (required)
     * @param  string $since The start date, inclusive, in yyyy-MM-dd format. (required)
     * @param  string $until The end date, inclusive, in yyyy-MM-dd format. (required)
     * @param  string[] $dimensions The dimensions, e.g. &#x60;query&#x60;, &#x60;page&#x60;. Must repeat for each dimension. (required)
     * @param  string $google_access_token The Google access token, must have access to the Google Search Console scope (required)
     * @param  string $cursor The cursor (optional)
     * @param  int $limit The maximum number of results (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listWebsiteSearch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listWebsiteSearchAsync($website, $since, $until, $dimensions, $google_access_token, $cursor = null, $limit = 10, string $contentType = self::contentTypes['listWebsiteSearch'][0])
    {
        return $this->listWebsiteSearchAsyncWithHttpInfo($website, $since, $until, $dimensions, $google_access_token, $cursor, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listWebsiteSearchAsyncWithHttpInfo
     *
     * List Website Search data
     *
     * @param  string $website The website URL (required)
     * @param  string $since The start date, inclusive, in yyyy-MM-dd format. (required)
     * @param  string $until The end date, inclusive, in yyyy-MM-dd format. (required)
     * @param  string[] $dimensions The dimensions, e.g. &#x60;query&#x60;, &#x60;page&#x60;. Must repeat for each dimension. (required)
     * @param  string $google_access_token The Google access token, must have access to the Google Search Console scope (required)
     * @param  string $cursor The cursor (optional)
     * @param  int $limit The maximum number of results (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listWebsiteSearch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listWebsiteSearchAsyncWithHttpInfo($website, $since, $until, $dimensions, $google_access_token, $cursor = null, $limit = 10, string $contentType = self::contentTypes['listWebsiteSearch'][0])
    {
        $returnType = '\OpenAPI\Client\Model\PageWebsiteSearch';
        $request = $this->listWebsiteSearchRequest($website, $since, $until, $dimensions, $google_access_token, $cursor, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listWebsiteSearch'
     *
     * @param  string $website The website URL (required)
     * @param  string $since The start date, inclusive, in yyyy-MM-dd format. (required)
     * @param  string $until The end date, inclusive, in yyyy-MM-dd format. (required)
     * @param  string[] $dimensions The dimensions, e.g. &#x60;query&#x60;, &#x60;page&#x60;. Must repeat for each dimension. (required)
     * @param  string $google_access_token The Google access token, must have access to the Google Search Console scope (required)
     * @param  string $cursor The cursor (optional)
     * @param  int $limit The maximum number of results (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listWebsiteSearch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listWebsiteSearchRequest($website, $since, $until, $dimensions, $google_access_token, $cursor = null, $limit = 10, string $contentType = self::contentTypes['listWebsiteSearch'][0])
    {

        // verify the required parameter 'website' is set
        if ($website === null || (is_array($website) && count($website) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $website when calling listWebsiteSearch'
            );
        }

        // verify the required parameter 'since' is set
        if ($since === null || (is_array($since) && count($since) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $since when calling listWebsiteSearch'
            );
        }

        // verify the required parameter 'until' is set
        if ($until === null || (is_array($until) && count($until) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $until when calling listWebsiteSearch'
            );
        }

        // verify the required parameter 'dimensions' is set
        if ($dimensions === null || (is_array($dimensions) && count($dimensions) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $dimensions when calling listWebsiteSearch'
            );
        }

        // verify the required parameter 'google_access_token' is set
        if ($google_access_token === null || (is_array($google_access_token) && count($google_access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $google_access_token when calling listWebsiteSearch'
            );
        }




        $resourcePath = '/ext/google/searchconsole/searches';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $website,
            'website', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $since,
            'since', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $until,
            'until', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $dimensions,
            'dimensions', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $google_access_token,
            'google_access_token', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listWebsites
     *
     * List
     *
     * @param  string $google_access_token The Google access token, must have access to the Google Search Console scope (required)
     * @param  int $limit The maximum number of results (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listWebsites'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\PageWebsite
     */
    public function listWebsites($google_access_token, $limit = 10, string $contentType = self::contentTypes['listWebsites'][0])
    {
        list($response) = $this->listWebsitesWithHttpInfo($google_access_token, $limit, $contentType);
        return $response;
    }

    /**
     * Operation listWebsitesWithHttpInfo
     *
     * List
     *
     * @param  string $google_access_token The Google access token, must have access to the Google Search Console scope (required)
     * @param  int $limit The maximum number of results (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listWebsites'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\PageWebsite, HTTP status code, HTTP response headers (array of strings)
     */
    public function listWebsitesWithHttpInfo($google_access_token, $limit = 10, string $contentType = self::contentTypes['listWebsites'][0])
    {
        $request = $this->listWebsitesRequest($google_access_token, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\PageWebsite' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\PageWebsite' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\PageWebsite', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\PageWebsite';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\PageWebsite',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listWebsitesAsync
     *
     * List
     *
     * @param  string $google_access_token The Google access token, must have access to the Google Search Console scope (required)
     * @param  int $limit The maximum number of results (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listWebsites'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listWebsitesAsync($google_access_token, $limit = 10, string $contentType = self::contentTypes['listWebsites'][0])
    {
        return $this->listWebsitesAsyncWithHttpInfo($google_access_token, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listWebsitesAsyncWithHttpInfo
     *
     * List
     *
     * @param  string $google_access_token The Google access token, must have access to the Google Search Console scope (required)
     * @param  int $limit The maximum number of results (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listWebsites'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listWebsitesAsyncWithHttpInfo($google_access_token, $limit = 10, string $contentType = self::contentTypes['listWebsites'][0])
    {
        $returnType = '\OpenAPI\Client\Model\PageWebsite';
        $request = $this->listWebsitesRequest($google_access_token, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listWebsites'
     *
     * @param  string $google_access_token The Google access token, must have access to the Google Search Console scope (required)
     * @param  int $limit The maximum number of results (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listWebsites'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listWebsitesRequest($google_access_token, $limit = 10, string $contentType = self::contentTypes['listWebsites'][0])
    {

        // verify the required parameter 'google_access_token' is set
        if ($google_access_token === null || (is_array($google_access_token) && count($google_access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $google_access_token when calling listWebsites'
            );
        }



        $resourcePath = '/ext/google/searchconsole/websites';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $google_access_token,
            'google_access_token', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
