<?php
/**
 * BotifyCrawlImportsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Wordlift\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Manager
 *
 * Subscription management and related services.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@wordlift.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Wordlift\Client\Test\Api;

use \Wordlift\Client\Configuration;
use \Wordlift\Client\ApiException;
use \Wordlift\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BotifyCrawlImportsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Wordlift\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BotifyCrawlImportsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createBotifyCrawlImport
     *
     * Create.
     *
     */
    public function testCreateBotifyCrawlImport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
